---
- name: Hardening GNU/Linux - Guide ANSSI BP-028
  hosts: all
  become: yes
  become_method: sudo
  become_user: root
  become_flags: '-H'

  vars:
    ansible_remote_tmp: /tmp/.ansible

  environment:
    ANSIBLE_REMOTE_TEMP: /tmp/.ansible
    ANSIBLE_HOST_KEY_CHECKING: "False"

  roles:
    - role: systeme
    - role: utilisateurs
    - role: fichiers
    - role: reseau
    - role: paquets
